#!/bin/sh
echo "Enter the year"
read y
a=$(expr $y % 4)
b=$(expr $y % 100)
c=$(expr $y % 400)
if ((( $a == 0 && $b != 0) || ($c == 0 )))
then
        echo "$y is leap year"
else
        echo "$y is not leap year"
fi
